

CREATE TABLE BITACORA_MOT_VISION(
        COD_BITACORA NUMBER,
        COD_MUDULO NUMBER,
        COD_TIPOMOD NUMBER,
        USUARIO_MODI VARCHAR(50),
        FEC_MODIFICA DATE,
         VALOR_ANTERIOR VARCHAR(50),
        VALOR_NUEVO VARCHAR(50)
);


CREATE SEQUENCE SEQ_BITACORA_MOT_VISION
START WITH 1
MAXVALUE 999999999999
MINVALUE 0
NOCYCLE
NOCACHE
NOORDER;

CREATE TABLE P_MODULO(
        COD_MODULO NUMBER,
        DES_MODULO VARCHAR(50)
);

INSERT INTO P_MODULO(COD_MODULO, DES_MODULO) VALUES(3, 'REGISTRO MECANICOS');
INSERT INTO P_MODULO(COD_MODULO, DES_MODULO) VALUES(4, 'REGISTRO USUARIOS');
INSERT INTO P_MODULO(COD_MODULO, DES_MODULO) VALUES(2, 'TALLER');
COMMIT;

CREATE TABLE P_TIPO_MODI(
        COD_TIPO_MODI NUMBER,
        DES_TIPO_MODI VARCHAR(50)
);

INSERT INTO P_TIPO_MODI(COD_TIPO_MODI, DES_TIPO_MODI) VALUES(1, 'MODIFIÓN NOMBRE');
INSERT INTO P_TIPO_MODI(COD_TIPO_MODI, DES_TIPO_MODI) VALUES(2, 'MODIFIÓN APELLIDOS');
INSERT INTO P_TIPO_MODI(COD_TIPO_MODI, DES_TIPO_MODI) VALUES(3, 'MODIFIÓN DOCCUMENTO IDENTIDAD');
INSERT INTO P_TIPO_MODI(COD_TIPO_MODI, COD_TIPOMOD) VALUES(4, 'MODIFIÓN DIRECCIÓN');
INSERT INTO P_TIPO_MODI(COD_TIPO_MODI, DES_TIPO_MODI) VALUES(5, 'MODIFIÓN NÚMERO DE TELEFONO');
INSERT INTO P_TIPO_MODI(COD_TIPO_MODI, DES_TIPO_MODI) VALUES(6, 'MODIFIÓN REFERENCIA');
COMMIT;

select BMV.USUARIO_MODI, 
          BMV.FEC_MODIFICA, 
          BMV.VALOR_ANTERIOR, 
          BMV.VALOR_NUEVO, 
          PM.DES_MODULO,
          PTM.DES_TIPO_MODI
from   BITACORA_MOT_VISION BMV,
          P_MODULO PM,
          P_TIPO_MODI PTM
WHERE BMV.COD_MUDULO = PM.COD_MODULO
AND     BMV.COD_TIPOMOD = PTM.COD_TIPO_MODI

/* CONSULTA  BITCORA propietario*/
SELECT PR.NOM_PROPIETARIO, 
	   PR.APE1_PROPIETARIO, 
	   PR.Doc_propietario, 
	   BITA.FEC_MODIFICA, 
	   BITA.VALOR_ANTERIOR, 
	   BITA.VALOR_NUEVO, 
	   BITA.USUARIO_MODI, 
	   MODU.DES_MODULO, 
	   MODI.DES_TIPO_MODI 
FROM   propietarios PR, 
       bitacora_mot_vision BITA, 
	   p_modulo MODU, 
	   p_tipo_modificacion MODI 
WHERE  PR.Doc_propietario = BITA.COD_REGISTRO 
AND	   BITA.COD_MODULO = MODU.COD_MODULO 
AND    BITA.COD_TIPO_MODI = MODI.COD_TIPO_MODI
and    BITA.COD_REGISTRO = 'dzh600b'